---
- name: "Remove old versions of docker"
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: "Add docker gpg key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    
- name: "Install docker deb"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"

- name: "Install new version of docker"
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present