---
- name: "Add kubernetes to source.list"
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes.list
  when: packages['kubectl'] is defined

- name: "Add kubernetes apt key"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  when: packages['kubectl'] is defined

- name: "Install SDK"
  apt:
    pkg: kubectl
    update_cache: yes
    cache_valid_time: 86000
  when: packages['kubectl'] is defined

# Minikube 
- name: "Install virtual box deb"
  apt:
    deb: https://download.virtualbox.org/virtualbox/6.1.10/virtualbox-6.1_6.1.10-138449~Ubuntu~bionic_amd64.deb
  when: packages['virtualbox*'] is defined

- name: "Install homebrew"
  apt:
    pkg: linuxbrew-wrapper
  when: packages['linuxbrew-wrapper'] is defined

- name: "Install minikube using brew"
  homebrew:
    name: minikube
  when: packages['minikube'] is defined